---
title: "School of Geography PGR Conference 2024"
---

Welcome to the School of Geography PGR Conference at the University of Leeds. The conference will take place on the **5th November 2024**, and is open to all PGRs here at the School of Geography!

The PGR conference has been a longstanding event within the School of Geography to showcase the exiciting and important research from postgraduates. The conference provides an opportunity for postgraduates to present ongoing research, network with peers and develop new insights in a friendly and constructive setting. It is hoped that all postgraduates from across the School of Geography attend, whenever presenting a talk, providing a poster, or coming along and engaging with your peers.

The School of Geography PGR conference will include:

-   15-min presentations from postgraduates
-   Keynotes speakers
-   Workshops
-   Poster session & networking opportunity
-   Lunch & social

If you would like to attend the conference (online or in-person), please register to attend via this form: XXXX. To present a research talk or a poster, more details are provided [here](Presentation.qmd).

### Key Dates

-   Deadline for presentation: Xth October 2024.
-   Deadline for poster: Xth October 2024.
-   Register to attend: Xth October 2024
-   SoG PGR Conference: 5th November 2024.
