---
title: "Poster"
---

Another way of presenting your research is by participating in our poster session. It provides an excellent way to showcase your current research and discuss informally to your peers. Posters are frequently used to communicate research during conferences, therefore the session provides a chance to produce a poster and practice delivering it. Also, the session is an opportunity to test ideas and feedback for your ongoing research. Therefore, we suggest posters are more suited to **2nd year PhD students**, however are open to all.

In order to present a poster, fill out the provided form ([**https://forms.gle/bYetCA111353cByV7**](https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fforms.gle%2FbYetCA111353cByV7&data=05%7C02%7Cgy17pls%40leeds.ac.uk%7Cdfa6a557325b4536e96608dcd968c89e%7Cbdeaeda8c81d45ce863e5232a535b7cb%7C0%7C0%7C638624291299365781%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=zcB%2FWBEG70WRJRpROYvFpilP81Ghz6JwszMqRShiraA%3D&reserved=0)) by the **11th of October,** detailing what your poster will focus on. Also, let us know if you already have a printed poster ready to go, or need help in producing one.

#### Guidelines for Poster

-   The poster can be portrait or landscape. Make sure it is readable and eye-catching!
-   We will provide materials to put up your poster.
-   Please come to the geography foyer before **9am** or during the first break (**11:00-11:15**) to put up your poster.
-   Be prepared to stand with your poster during the poster session (**12:30-13:30**) and discuss your research.

There will be an award for the best poster decided by attendees during the poster session using Menti (\<insert link\>).
