---
title: "Abstracts"
---

## Session 1: Case Studies {#sec-session-1-case-studies}

### Yue Che, SJCC {#sec-yue-che-sjcc}

**Title:** Uneven Entrepreneurial Governance: Imagining Urban Regeneration in State-Owned Industrial Communities of Chinese Small Industrial City 

**Abstract:**

### Lauren Cape-Davenhill, SJCC {#sec-lauren-cape-davenhill-sjcc}

**Title:** 'Abnormal justice' for non-nationals

**Abstract:** *This presentation explores the ways in which the criminal justice and immigration systems intersect to produce 'abnormal justice' (Aas 2014) for non-citizens in the UK. It shows how people categorised as 'foreign national offenders' experience harsher penalties within the criminal justice system, and a focus on deportation as a response to criminality, thus calling principles of justice including proportionality and rehabilitation into question. It is based on PhD fieldwork conducted with people facing deportation following contact with the criminal justice system.* 

### Sanola Sandiford, EGC {#sec-sanola-sandiford-egc}

**Title:** Modelling Climate Impacts, Responses and Adaptation Options for Indigenous Communities in Greenland

**Abstract:** *The island of Greenland in the Arctic circle is expected to undergo a significant environmental transformation due to climate change. Travel and transportation routes are likely to be affected as a result, particularly the ice, sea and land trails that Inuit communities traverse on a regular basis. The degradation of trails will make travel across Greenland much more challenging, particularly for inhabitants of the most remote settlements. This research intends to examine potential solutions to this climate issue by incorporating both scientific data and indigenous knowledge. It also aims to examine the social importance of trails across Greenland and the social and economic impacts that the total or partial degradation of trails may have on locals. Climate model projections will be employed to examine possible climate impacts on trail use over the next century and will be combined with indigenous knowledge to create trail access models, which outline when trails may become unusable. Further collaboration with indigenous Greenlanders will occur to determine effective adaptation and mitigation strategies. The opinions and knowledge of indigenous people will be placed at the forefront of this research as they often tend to be overlooked in research and decision-making processes that directly affect them.* 

### Arwanto, SJCC {#sec-arwanto-sjcc}

**Title:** Refugee Educational Opportunities in Indonesia

**Abstract:**

### Jinnawat Lertpradit, SJCC {#sec-jinnawat-lertpradit-sjcc}

**Title:** Co-creating local curriculum on environmental education and indigenous knowledge systems: a case study of place-based education in Chiang Mai's schools

**Abstract:** *This research explores the integration of Environmental Education (EE) and Indigenous Knowledge Systems (IKS) into a place-based education (PBE) curriculum within Chiang Mai's secondary schools. Using a participatory action research approach, the study collaborates with teachers, students, parents, and community members from two selected schools to co-create a curriculum that promotes environmental awareness while respecting indigenous knowledge and practices. The research investigates the extent to which PBE is currently practised in Chiang Mai's schools, the challenges involved in its implementation, and how educational policies at national, regional, and local levels influence or hinder this approach. It also examines the impact of power relations on access to and participation in PBE and IKS, with a particular focus on equity and inclusivity within the educational context. Data collection methods include interviews and focus group sessions, workshops, document analysis, and participatory activities, analysed through a thematic approach.*  

### Youhua Chen, SJCC {#sec-youhua-chen-sjcc}

**Title:** State-led mega urbanization project in inner Shanghai, China

**Abstract:**

## Session 2: Rivers and Pollution

### Zhangling Chen, RBPM {#sec-zhangling-chen-rbpm}

**Title:** Transport Mechanisms of Microfibers and Their Effects on Soil-Plant Systems

**Abstract:** *Microplastics (MPs) have become a global environmental concern due to uncertainties regarding their occurrence, fate, and potential implications for environmental and human health. While research on the impact of MPs in aquatic systems is expanding, studies on their influence on terrestrial systems remain limited. Agricultural soils serve as a major reservoir for MPs, with microfibers (MFs) being a predominant form due to activities like clothing washing and applying organic amendments. Despite their prevalence, the mechanisms of MF transport and their effects on soil-plant systems are still largely unknown. This study addresses key knowledge gaps by conducting soil incubation experiments to investigate the impact of polyester (PES) MFs on soil properties and the performance of three common crops: lettuce (Lactuca sativa), Chinese cabbage (Brassica rapa subsp.), and radish (Raphanus sativus). The crops were cultivated in glass jars containing soil mixed with 100 mg/kg of fluorescent MFs, and MF distribution was visualized using the EVOS Auto FL 2 system. The results revealed that MFs significantly reduced soil bulk density (p \< 0.05). However, their impact on soil water holding capacity and total organic carbon content was minimal across all treatments (p \> 0.05). Additionally, variations in soil pH were observed depending on the crop species (p \< 0.05). Differences in the proportion of small macroaggregates were also detected in soils containing microfibers (p \< 0.05). In terms of plant performance, the presence of MFs significantly accelerated the early germination and harvested root length of lettuce (p \< 0.05). In contrast, they decreased total chlorophyll content in lettuce and Chinese cabbage leaves, whereas an increase was observed in radish leaves (p \> 0.05). Furthermore, MFs accumulated in the rhizosphere soil and adhered to lettuce root surfaces, with fluorescence also observed in both lettuce roots and leaves, suggesting potential uptake. The study highlights species-specific responses to MFs, demonstrating a range of effects---from negative to neutral or positive---on soil properties and plant performance. These effects are likely due to the unique characteristics of MFs, including their shape, surface area, and flexibility, which influence their interactions with soil particles and crops. Given the widespread presence and accumulation of MFs in agricultural soils, this research provides crucial insights for ecotoxicological assessments of soil and terrestrial plants. It also holds important implications for environmental pollution, food safety, and human health.*

### Tom Nash, RBPM {#sec-tom-nash-rbpm}

**Title:** Microplastic-induced genotoxicity in Daphnia pulex

**Abstract:** *Daphnia are a genus of freshwater crustacean, highly sensitive to environmental pollutants and used routinely for freshwater quality testing. Exposure to microplastics is known to negatively impact Daphnia, causing increased mortality and a range of sublethal effects. Genotoxicity is the ability of a substance to damage genetic information. Measuring genotoxicity can provide a useful endpoint since it can detect sublethal -- but still potentially harmful -- effects across varied timescales. Combined with other biomarkers, genotoxicity testing can improve understanding of the ecological consequences of environmental contamination. Daphnia pulex (n = 560) were exposed to 100nm polystyrene microparticles for 24 and 48 hours at doses ranging from 10 to 200 mg/L, with immobilisation (mortality) and genotoxicity endpoints assessed following exposure. Results indicate that polystyrene microparticles at high concentrations induce genotoxicity within 48 hours, however immobilisation proved more sensitive to the presence of polystyrene microparticles at both lower concentrations and after just 24 hours.* 

### Di Wu, RBPM {#sec-di-wu-rbpm}

**Title:** Effects of polystyrene microplastics on freshwater organisms

**Abstract:** *As an emerging contaminant, microplastics have been widely detected in freshwater systems, posing threat to various freshwater organisms and ecosystems. However, there is still limited knowledge about the effects of microplastics on fish health and freshwater-sediment ecosystem interactions. In this research, polystyrene microplastics induced gender-specific toxicity to adult zebrafish by affecting gut microbiota, liver metabolism and reproductive process. In addition, a freshwater-sediment microcosm consist of submerged plants and snails was more affected by irregular polystyrene microplastics than regular microplastics. Irregular microplastics could inhibit photosynthesis and induce oxidative stress of plants; induce oxidative stress and influence metabolism of snails; change the basic property of sediment and water, therefore affect the whole microcosm.*

### Beany Townsend, RBPM {#sec-beany-townsend-rbpm}

**Title:** Quantifying sediment loss from riverbanks attributable to the presence of invasive impatiens glandulifera

**Abstract:** *There is a prevailing misconception that the invasive plant Impatiens glandulifera causes erosion along riparian corridors through displacing native vegetation during the growing season, reducing above ground canopy structure and affecting root-soil interactions. Once this dominant plant dies back in the autumn, large areas of riverbank are then left unprotected from sub-aerial erosive processes resulting in increased sediment loss. There is however a lack of data strongly supporting the argument that I. glandulifera negatively impacts native plant communities and even less data to conclusively link it to causing erosion. In-situ erosion plots were used to monitor run off from riverbanks typified by both native communities, and I. glandulifera. Sediment loss was measured for 42 replicate plots across 7 sites on a monthly basis over the course of 339 days between December 2021 and October 2022. Data was also collected on I. glandulifera stem density and percentage cover, rainfall, and soil particle size. The results show that total annual sediment loss was higher from native vegetation plots (210 g) than from I. glandulifera plots (176 g). Seasonal data did not show a large increase in sediment flux for I. glandulifera plots in the autumn, at the time when the plant was naturally dying back as anticipated, with levels not significantly different from native vegetation plots. Plots with either high percentage cover or stem density m-1 showed some resilience to erosion leading to the conclusion that large amounts of above ground canopy and stem growth presumably coupled with root abundance confers some erosive resilience in the summer that negates any negative effects of a loss of organic matter in the winter. These results show that I. glandulifera should not be managed for the risk it poses to riverbank erosion and lessons could be learnt in erosion mitigation and habitat management through better understanding why I. glandulifera does not have the anticipated negative effect on sediment loss.*

### T. Kulangana, RBPM {#sec-t.-kulangana-rbpm}

**Title:** Quantifying Methane Fluxes and Environmental Influences in UK Freshwater Ecosystems: A Spatio-Temporal Study

**Abstract:** *Methane is a potent greenhouse gas with a significant contribution to global climate change. Inland freshwater bodies are critical contributors to atmospheric methane (Rosentreter et al. 2021), accounting for substantial uncertainty in the global methane budget. Therefore, understanding the variability of methane emission and the drivers of these emissions is essential to improving our estimates of global methane fluxes. In this study, we aim to measure and compare the diffusive flux of methane in selected rivers using the floating chamber method and dissolved gas sampling. We will examine the relationship between methane concentrations and river discharge and analyse the seasonal variability of methane emissions across different sites and rivers. Additionally, we will correlate methane emissions with environmental variables such as water temperature, pH, dissolved oxygen, conductivity, pressure, and dissolved organic carbon. The study sites, Ryburn and Loxley River (connected to Ryburn, Booth wood and Damflask reservoirs) each have three sampling points, along with nearby control sites. We have successfully completed a two-week field campaign for collecting gas flux data, nutrient data, metabolism data, and dissolved gas data from these two rivers during a reservoir-controlled flow release and data were collected on the same day as a score test. We are now sampling every three weeks for time series data, with plans to continue for up to one year. Key tools and equipment include floating chambers, gas analysers, dissolved oxygen loggers, and gas chromatographs. Therefore, this study aims to reduce the uncertainties surrounding methane emissions from freshwater ecosystems by providing robust spatio-temporal data on diffusive emission and drivers. The findings will be critical for informing large-scale methane emission models and developing targeted mitigation strategies for aquatic environments, advancing both scientific inquiry and environmental policy related to climate change.* 

### 

## Session 3: Triple A - Art, Agriculture, and Agent-Based Models

### Katie Lee, SJCC {#sec-katie-lee-sjcc}

**Title:** Embedding public art: a long term approach to serving post-industrial communities

**Abstract:** *The site of Markham Vale may not look like an abandoned coal-mine, unless you know the signs. There is a small plaque here, some remnants of machinery there, plus a walking trail of unrealistic figures marking the way to the closest village. Here, a complex web of stakeholders has spent over ten years on a public art project. They have shared stories of the past with younger residents, brought together long lost relatives, and provided an anchor to remember those who died in mining disasters over the years. This case study explores an unconventional example of public art that provides lessons for future practice and a suggested formative model for evaluation.*

### Rafa Mendes-Browne, SJCC {#sec-rafa-mendes-browne-sjcc}

**Title:** The Production of Racially Mixed Identity in the British Music Industry

**Abstract:** *Promoting and understanding racial and ethnic equality within the British music industry has had growing interest in both academic and music industry communities. However, research surrounding minority representation in British music tends to focus on monoracial musicians' experiences with little attention given to challenges faced by racially Mixed music professionals. Racially Mixed people find themselves categorised within other racial groups, with these miscategorisations disregarding and diminishing the visibility of the distinct experiences racially Mixed people have compared to other minorities. My research uses methods including improvisatory jam sessions, post-jam interviews and autoethnographic journaling. Through combining musical and ethnographic data, this experimental research design, inspired by themes of identity, representation, and participant-researcher intimacy via cultural production, provides an in-depth analysis of the connections between racially Mixed identity, creativity, and a musician's 'Creative Personal Identity' (Culpepper & Gauntlett, 2021). This paper will explore the methodological framework informing my research, which aims to provide a platform centred on amplifying the experiences of racially Mixed musicians in rock, pop and jazz communities in the UK. The analytical framework used to explore the themes and topics shared by racially Mixed musicians in interviews will be discussed in relation to what responsibility music industry bodies have in fostering racially Mixed talent, and how music culture contributes to the creation of racially Mixed identities. In addition, analysis of excerpts from the jam sessions will be used to explore the musical expression of racially Mixed identities.*

### Andi Pratiwi, SJCC {#sec-andi-pratiwi-sjcc}

**Title:** Feminist Participatory (Creative) Action Research on Climate Change

**Abstract:**

### Beth Adams, RBPM {#sec-beth-adams-rbpm}

**Title:** Pecking Away at Pollution: The Environmental Challenge of Veterinary Medicines in Poultry Litter!

**Abstract:** *This presentation will discuss the results of a study that aimed to examine the environmental impact of veterinary medicines and feed additives in poultry litter and evaluates the efficacy of the current risk assessment processes. Currently, most research focuses on pig and cattle manure, leading to guidelines that may not apply to poultry litter, which is less well researched. The variability in poultry litter properties and how it affects the degradation of these medicines is not well understood.  An experiment was conducted using poultry litter from different farms to assess the degradation of five key veterinary antimicrobials: tiamulin, trimethoprim, sulfadiazine, monensin, and salinomycin to see if there were any differences between degradation rates between different farms. The results showed significant differences in degradation rates of all antimicrobials tested among different poultry litters. This suggests a need for more research on the properties of poultry litter to improve environmental risk assessments.* 

### Xitong Dai, ISDS {#sec-xitong-dai-isds}

**Title:** Simulating Social Network Impacts on Meat-Eating Patterns: An Agent-Based Approach

**Abstract:** *Diet is pivotal in shaping individual and public health outcomes and significantly affects land use and sustainability within the food system. Understanding the factors influencing dietary choices is essential for promoting healthier and more sustainable consumption patterns, especially as global food demand rises. Research indicates that dietary habits are strongly influenced by social networks, where the behaviours and opinions of peers can reinforce or alter individual dietary choices. This study focuses on meat consumption, which has considerable implications for health, environmental sustainability, and animal welfare. Employing an agent-based model (ABM) informed by survey data, the research investigates the dynamics of meat-eating behaviours by analyzing demographic characteristics, social networks, and the Theory of Planned Behaviour (TPB). The survey collects data on participants' meat consumption, demographic details, and social influences from their top ten most interacted individuals. The ABM simulates individual decision-making processes based on TPB attributes---attitudes, subjective norms, and perceived behavioral control---allowing for the exploration of how these factors shape meat consumption patterns. This approach aims to provide insights that can inform public policy, health interventions, and educational campaigns aimed at fostering sustainable dietary practices.*

### Kejian Li, ISDS {#sec-kejian-li-isds}

**Title:** Case Study on Calibration Methods for a High-Dimensional Global Trade Agent-Based Model

**Abstract:** *This study conducts a case study on calibration methods for a high-dimensional global trade agent-based model. We compare the efficacy of Latin Hypercube Sampling (LHS), Genetic Algorithms (GA), and approximate Bayesian Computation (ABC) in calibrating this complex model. LHS explores the parameter space comprehensively, GA optimizes effectively, and ABC combines exploration with statistical inference. Our findings show the strengths and weaknesses of each method, highlighting the need to choose calibration methods suited to the model's dimension- ality and complexity. This study offers useful insights for researchers and practitioners working with high-dimensional agent-based models.*

## Session 4: Earth Observation of Dry and Wet

### Jisung Kim, EGC {#sec-jisung-kim-egc}

**Title:** Spatio-temporal trends and processes in desertification in Africa and Europe

**Abstract:** *Desertification is a silent, invisible crisis that is destabilizing communities on a global scale. Reliable and continuous monitoring is required for combating desertification. However, finding consistent and efficient monitoring frameworks for multiple-attribute phenomena is challenging, including desertification. Thus, my research aims are a) to devise a new framework for monitoring multiple-attribute phenomena and b) to apply it to measure desertification.* 

### Denise Hick, EGC {#sec-denise-hick-egc}

**Title:** The reflectance behaviour of European soils with increasing soil moisture content

**Abstract:** *The satellite reflectance of bare soil is increasingly being used as a covariate in models that predict the quantity of soil properties in the top few centimetres of soil. One of the main factors affecting the reflectance of soil, leading to skewed soil property predictions, is moisture content. This study aimed to explore the relationship between soil reflectance and soil moisture content using spectroscopy. The reflectance behaviour of 28 soil samples from across Europe was investigated in the laboratory following the addition of water to each sample. Initial findings show that different European soils can behave slightly differently with increasing soil moisture content. We investigate whether soil properties like texture, organic carbon, carbonate and iron content can explain this variability, and discuss the implications for future remote sensing studies that rely on satellite reflectance for topsoil property prediction.* 

### Connie Harpur, RBPM {#sec-connie-harpur-rbpm}

**Title:** Ice Marginal Lakes Enhance Glacier Velocities across Greenland

**Abstract:**

### Jamie Izzard, RBPM {#sec-jamie-izzard-rbpm}

**Title:** Using ICESat-2 to estimate the Depth of Supraglacial Ponds

**Abstract:** *Supraglacial ponds regulate the dynamics of mountain glaciers, by temporarily storing meltwater that would otherwise reach the ice-bed interface and promote sliding. However, their sudden drainage can also rapidly inject large amounts of water into the bed, causing short term accelerated ice flow. Additionally, their low albedo and association with bare, debris-free ice cliffs promote strong, localized ablation. Previous research has studied the spatio-temporal distribution of supraglacial ponds, although attempts to link this to glacier dynamics have generally been hampered by the uncertainty of the water volume stored within these ponds. Studies typically rely on simple empirical relationships between pond area and volume, based on a small number of in-situ measurements of depth. We showcase here a new method to retrieve the depth and volume of supraglacial ponds from ICESat-2 laser altimetry data. We identify ICESat-2 tracks that intersect with empty supraglacial ponds and match these with optical imagery of the ponds when they are full. We then use these measurements to refine these empirical relationships and estimate glacier-wide supraglacial water storage. We then analyse the spatio-temporal distribution of ponds on the glacier surface and compare these to velocity measurements derived from Sentinel-1 feature tracking to investigate the relationship between supraglacial ponds and ice dynamics.* 
