---
title: "Presentation"
---

We invite all SoG postgraduates the opportunity to present some research. This could be an aspect of your PhD thesis, or a research project/paper that you have contributed to. It is expected that presentations are most suited to **3rd year PhD students**, however are open to all. Presentations should be **10 minutes**, followed by **5 minutes** of Q/A.

In order to present, please submit an abstract of your research (around 300 words) by the **11th of October** using this form ([**https://forms.gle/bYetCA111353cByV7**](https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fforms.gle%2FbYetCA111353cByV7&data=05%7C02%7Cgy17pls%40leeds.ac.uk%7Cdfa6a557325b4536e96608dcd968c89e%7Cbdeaeda8c81d45ce863e5232a535b7cb%7C0%7C0%7C638624291299365781%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=zcB%2FWBEG70WRJRpROYvFpilP81Ghz6JwszMqRShiraA%3D&reserved=0)). This is to help position your presentation within the appropriate thematic session. This should not be an exhaustive task, all is required is a brief summary of the research you want to present.

#### Guidelines for Presenting

-   The presentation must be 10 minutes, so please keep to the timings. It will be great practice for future conferences that might be a bit more strict!
-   Audience will have the opportunity to ask questions to the presenter for 5 minutes, directly after the presentation.
-   The session chair will help manage time, notifying when there are a few minutes left and coordinating the following Q/A.
-   **Presenting in-person:** The PowerPoint presentation must be saved on a USB drive. It is recommended to arrive a few minutes before the session start to upload the presentation onto the laptop.
-   **Presenting online:** Ensure you have entered the Teams session using the links provided (will be uploaded on website & sent via email) and that your camera and microphone are working correctly.
-   Enjoy the experience! The PGR conference will be a relaxed and positive environment. It will be a great opportunity to practice your presentation skills and test out your ideas.

There will be an award for the best human geography and physical geography paper, chosen by conference committee.
